### ISSUE TITLE
Methods feedback

### ISSUE THREAD

**Issue by ericward-noaa** [Evfrench/KC-Streams-Analysis#4]
Good job on pulling this together -- it's a good use of DLMs. I was wondering if some of the convergence issues / etc might be due to the number of covariates included? I assume you'd run some simpler models -- but wasn't sure if using a model with 2-3 covariates might give you results that were reasonable? I think if all covariates were standardized, you could look at the relative magnitudes of coefficients + drop those that are smallest in magnitude?

**Comment by Evfrench** [comment]
Hi Eric! You know I actually have not run simpler models yet, but I am starting to consider doing so. The reason why I have so many covariates in the DLM is because they are what is used by the WRTDS model. My first inclination was to set up both models as similarly as I could, then compare and contrast how each one handled the data and what trends they could identify. I have considered dropping some covariates like you suggest, though I am a little reluctant at the moment. However, I will definitely try standardizing the covariates. I had not considered that before. I appreciate the feedback!

**Comment by eeholmes** [comment]
Hi Eric F, Ditto re getting this together and getting the DLM and weighted regression working. We have had a couple discussions on how to fix the DLM model not tracking the mean level of the data. I put in a couple pull requests to show a fix to that. With Q=1e-6 for the level (intercept aka X1), it now tracks the dip in the level around t=200. I don't think you need to do any of the other things that I suggested on Thursday (polynomials or year factor). But if you want to try one of those, then use a year factor not the polynomial; on further reflection I think the polynomial would need too many orders.

One interesting aspect that you'll see in my pull request is that it seems there is support for a changing timing of the peak since X4 has a linear trend to it. 

In the 2nd pull request, I show a function you can use to figure out the time of the peak based on the X4 and X5 values. This shows that the peak has shifted by about a week later in the year while the amplitude is roughly steady.

**Comment by eeholmes** [comment]
Here is the image with the level variance at 1e-6. Notice the level shift and now the X4 is trending upward.

<img width="1009" alt="image" src="https://github.com/Evfrench/KC-Streams-Analysis/assets/2545978/9dfbba33-8892-4ea6-9b9a-d9e0c7afcf7b">

Here is the location of the peak. 0 = Jan 1, 1 = Feb-1, 2 = Mar-1 (so y axis scale is non-intuitive). So you can see that the peak is just after Feb 1 and then jumps to Mar-1 at the that weird time and then is 1-2 weeks later after that.

<img width="895" alt="image" src="https://github.com/Evfrench/KC-Streams-Analysis/assets/2545978/990db30a-f459-43ff-a75f-04e862472f28">
